### ISSUE TITLE
Bug in "follow_joint_trajectory.cpp" ?

### ISSUE THREAD

**Issue by chuong98** [fetchrobotics/robot_controllers#12]
Hi, Can you double check if the following code (from line 456 -475) in the file "follow_joint_trajectory.cpp " has a bug?

```
 // Convert the path tolerances into a more usable form
    for (size_t j = 0; j < joints_.size(); ++j)
    {
      int index = -1;
      for (size_t i = 0; i < goal->path_tolerance.size(); ++i)
      {
        if (joints_[j]->getName() == goal->path_tolerance[i].name)
        {
          index = i;
          break;
        } //??????
        if (index == -1)
        {
          result.error_code = control_msgs::FollowJointTrajectoryResult::INVALID_JOINTS;
          server_->setAborted(result, "Unable to convert path tolerances");
          ROS_ERROR("Unable to convert path tolerances");
          return;
        }
        path_tolerance_.q[j] = goal->path_tolerance[i].position;
        path_tolerance_.qd[j] = goal->path_tolerance[i].velocity;
        path_tolerance_.qdd[j] = goal->path_tolerance[i].acceleration;
      }//end second for
    } //end first for
```

To me, the  following changes make more sense

```
    for (size_t j = 0; j < joints_.size(); ++j)
    {
      int index = -1;
      for (size_t i = 0; i < goal->path_tolerance.size(); ++i)
      {
        if (joints_[j]->getName() == goal->path_tolerance[i].name)
        {
          index = i;
          break;
        }
      } // end second for
        if (index == -1)
        {
          result.error_code = control_msgs::FollowJointTrajectoryResult::INVALID_JOINTS;
          server_->setAborted(result, "Unable to convert path tolerances");
          ROS_ERROR("Unable to convert path tolerances");
          return;
        }
        path_tolerance_.q[j] = goal->path_tolerance[index].position;
        path_tolerance_.qd[j] = goal->path_tolerance[index].velocity;
        path_tolerance_.qdd[j] = goal->path_tolerance[index].acceleration;

    } //end first for
```

And similar question for the part : // Convert the goal tolerances into a more usable form

**Comment by mikeferguson** [comment]
Can you explain what you think the bug is? What is or is not happening that causes you to think there is a bug?

**Comment by mikeferguson** [comment]
Ok, after editing your question to get better formatting, I see what you are noting.

**Comment by mikeferguson** [comment]
Should be fixed as part of https://github.com/fetchrobotics/robot_controllers/pull/13. If you try that out and it works for you, we can merge that and release it ASAP.

**Comment by chuong98** [comment]
Thank you. The new code works for me. I added the following code to the fetch_gazebo_demo/demo.py for quick testing:
(in function "move_to" of class FollowTrajectoryClient)
follow_goal = FollowJointTrajectoryGoal()
        follow_goal.trajectory = trajectory
        follow_goal.path_tolerance.append(JointTolerance())
        follow_goal.path_tolerance[0].name = self.joint_names[0];
        follow_goal.path_tolerance[0].position = 0.03;
        follow_goal.path_tolerance[0].velocity = 0.03;
        follow_goal.path_tolerance[0].acceleration = 0.03;
and run the launch file demo.launch
