### ISSUE TITLE
Member  variable updated after return statement

### ISSUE THREAD

**Issue by cpitts1** [fetchrobotics/robot_controllers#21]
I was looking through robot controllers and was trying to understand the code contained in the file pid.cpp. I found that the member variable error_last_ was updated after a return statement:

https://github.com/fetchrobotics/robot_controllers/blob/indigo-devel/robot_controllers/src/pid.cpp#L161

This seemed like a problem to me unless there is a C++ trick that I don't know about

**Comment by mikeferguson** [comment]
No magic -- this is just plain wrong. A quick look through repos shows that this isn't actually being used anywhere quite yet:
- our gazebo sim mainly uses the control_toolbox implementation
- our gazebo parallel gripper controller does use this but has d-gain of 0.0
- Cartesian controllers use this, but aren't even configured for Fetch

As such, we can fix it without much issue -- go ahead an open a PR when you get a chance.

**Comment by mikeferguson** [comment]
https://github.com/fetchrobotics/robot_controllers/pull/22
