### ISSUE TITLE
Change default branch to ros1?

### ISSUE THREAD

**Issue by mikeferguson** [fetchrobotics/robot_controllers#73]
@erelson should we change the default branch to ros1? (Which AFAIK will actually work on both melodic + noetic, which are the only supported ROS1 distros out there).

I was going to open a PR for some additional documentation so we can close a few issues that are mainly asking questions, planning to open against ros1 and would like that README stuff to be on the front page.

**Comment by erelson** [comment]
I can do this, and it's a good time, since we're shipping some freights with Noetic soon.

**Comment by erelson** [comment]
All set.
